### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by Coder-256** [christopherm99/cws-service#1] opened 2019-01-30 05:47 UTC
please. before it's too late. don't fall down the npm rabbit hole! or the linting rabbit hole! or the travis rabbit hole! don't make my mistakes, it's only bikeshedding and distracting!

i took a look at your project and it is honestly pretty great so far! but a piece of advice: stop worrying about npm. it is horrible, horrible software. it gives me nightmares whenever i try to sleep. reset your .travis.yml to e903129. add `.firebase` to your `.gitignore`. then replace `eslint` with `npx eslint` in ur scripts and that should make it work. if not, i would recommend just focusing on the actual code, don’t worry about CI! and let me know if u need any other help i’m extremely bored

**Comment by Coder-256** [comment] 2019-01-30 05:51
oh my god the horror your travis config is polluted CHRIS FOCUS this is not progress! i made the same mistakes. don't make them too! use `npx` for your scripts and `npm-check-updates` to automate managing `npm`'s nightmare of packages. or if that doesn't work give up on linting and focus on coding! before it's too late stop worrying about that stuff! i wasted so much time on that. this is probably one of the most important advice i have for you. but in the end it's your project not mine

**Comment by christopherm99** [comment] 2019-01-30 13:57
Hey it works now! Also it's setup to cache the .npm folder, so I can feel slightly better about the whole Travis environment.

**Comment by christopherm99** [comment] 2019-01-30 13:59
The issue is not in the linting on Travis, that runs fine, but on the firebase deploy, specifically deploying the cloud functions and firestore security rules.

**Comment by Coder-256** [comment] 2019-01-30 15:29
welp PR time i guess i'll show u what i mean

**Comment by christopherm99** [comment] 2019-01-30 20:57
#2 has been merged. Closing

**Closed by christopherm99** 2019-01-30 20:57 UTC
Labels: enhancement
